import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 10, paddingTop: 50 },
  leftRow: { flexDirection: 'row', alignItems: 'center' },
  hostInfo: { flexDirection: 'row', alignItems: 'center' },
  avatar: { width: 40, height: 40, borderRadius: 20 },
  hostName: { color: '#fff', marginLeft: 1 },
  follow: { backgroundColor: '#E76A54', borderRadius: 12, paddingHorizontal: 10, paddingVertical: 4, marginLeft: 6 },
  viewerInfo: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#E76A54', borderRadius: 12, paddingHorizontal: 8, paddingVertical: 4, marginRight: 30 },
  viewerCount: { fontWeight: 'bold', color: '#fff' },
  sideToolbar: { position: 'absolute', right: 10, top: 200, gap: 14 },
chatOverlay: { 
  position: 'absolute', 
  left: 0, 
  right: 0, 
  maxHeight: 200,
  paddingHorizontal: 5,
  zIndex: 2,
  bottom: 200,
  borderTopLeftRadius: 12,
  borderTopRightRadius: 12,
  borderBottomLeftRadius: 0,
  borderBottomRightRadius: 0,
  paddingVertical: 8,
  overflow: 'hidden', // required for blur to be clipped
},
chatMessage: {
  fontSize: 14,
  fontWeight: '500',
  color: '#fff',
  lineHeight: 20,
},
  chatSender: {
    fontWeight: 'bold',
    color: '#E76A54',
  },
  chatInputWrapper: { 
    position: 'absolute', 
    bottom: 10, 
    left: 10, 
    right: 10, 
    flexDirection: 'row', 
    alignItems: 'center', 
    backgroundColor: 'rgba(28, 28, 28, 0.95)', 
    borderRadius: 20, 
    paddingHorizontal: 10, 
    paddingVertical: 6, 
    marginBottom: 10,
    zIndex: 2,
  },
  chatInput: { 
    flex: 1, 
    color: '#fff', 
    fontSize: 14, 
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  sendButton: { 
    color: '#E76A54', 
    fontWeight: 'bold', 
    marginLeft: 8,
    fontSize: 14,
  },
  productPanel: { 
    position: 'absolute', 
    bottom: 100,
    left: 10, 
    right: 10, 
    borderRadius: 12, 
    flexDirection: 'row', 
    alignItems: 'center', 
    padding: 12, 
    marginBottom: 10,
    zIndex: 2,
  },
  productPanelBlur: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    borderRadius: 0,
    overflow: 'hidden',
    zIndex: 1,
    height: 200,
  },
  imageContainer: {
    width: 60,
    height: 60,
    borderRadius: 8,
    overflow: 'hidden',
    marginRight: 10,
    backgroundColor: '#2a2a2a',
  },
  loadingContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  productImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  productDetails: {
    flex: 1,
    
  },
  priceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  originalPrice: {
    color: '#fff',
    fontSize: 12,
    textDecorationLine: 'line-through',
    marginRight: 6,
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  productPrice: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  feesText: {
    color: '#fff',
    fontSize: 12,
    marginLeft: 4,
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  seeMoreButton: {
    color: '#E76A54',
    fontSize: 12,
    marginLeft: 8,
    textDecorationLine: 'underline',
  },
  priceDetailsModal: {
    position: 'absolute',
    bottom: 70,
    right: 10,
    backgroundColor: 'rgba(26, 26, 26, 0.95)',
    borderRadius: 12,
    padding: 12,
    zIndex: 3,
  },
  priceDetailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  priceDetailLabel: {
    color: '#fff',
    fontSize: 12,
  },
  priceDetailValue: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  discountBadge: {
    backgroundColor: '#E76A54',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    marginLeft: 6,
  },
  discountText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
  },
  productTitle: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
    flex: 1,
    marginRight: 8,
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  productDescription: {
    color: '#fff',
    fontSize: 12,
    marginBottom: 4,
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  metaContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: -8,
  },
  stockContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  productMeta: {
    color: '#fff',
    fontSize: 11,
    marginLeft: 4,
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  timerBox: {
    backgroundColor: '#E76A54',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 8,
  },
  timerText: {
    color: '#000',
    fontWeight: 'bold',
    fontSize: 12,
    marginLeft: 4,
  },
  emptyPanel: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  emptyPanelText: {
    color: '#ccc',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 8,
  },
  bottomBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    position: 'absolute',
    bottom: 70,
    left: 0,
    right: 0,
    paddingHorizontal: 10,
    zIndex: 1,
    height: 50,
  },
  buyButton: {
    flex: 1,
    height: 50,
    backgroundColor: '#E76A54',
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 10,
  },
  buyButtonDisabled: {
    backgroundColor: '#666',
    opacity: 0.7,
  },
  buyButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  customBtn: { backgroundColor: '#fff', padding: 10, borderRadius: 8 },
  bidBtn: { backgroundColor: '#E76A54', padding: 10, borderRadius: 8 },
  shopIcon: { backgroundColor: '#fff', padding: 10, borderRadius: 20 },
  purchaseBanner: { position: 'absolute', top: 200, alignSelf: 'center', backgroundColor: '#222', paddingVertical: 6, paddingHorizontal: 12, borderRadius: 20 },
  purchaseBannerText: { color: '#E76A54', fontSize: 14, fontWeight: 'bold' },
  backButtonWrapper: { backgroundColor: 'rgba(0,0,0,0.4)', borderRadius: 20, padding: 6 },
  waitingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  waitingText: { color: '#fff', fontSize: 18 },
  qtyButton: { 
    width: 40,
    height: 40,
    backgroundColor: 'rgba(231, 106, 84, 0.95)',
    paddingHorizontal: 10, 
    paddingVertical: 4, 
    borderRadius: 20,
    marginHorizontal: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  qtyButtonText: { 
    color: '#fff', 
    fontWeight: 'bold', 
    fontSize: 20,
  },
  qtyText: { 
    color: '#fff', 
    fontSize: 18, 
    fontWeight: 'bold',
    minWidth: 30,
    textAlign: 'center',
  },
  swipeButton: {
    flex: 1,
    height: 50,
    marginLeft: 10,
    borderRadius: 25,
    overflow: 'hidden',
  },
  swipeRail: {
    backgroundColor: 'rgba(231, 106, 84, 0.95)',
    borderRadius: 25,
  },
  swipeThumb: {
    backgroundColor: '#fff',
    borderRadius: 25,
    width: 50,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  swipeTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  chatMessageWrapper: {
    backgroundColor: 'rgba(0,0,0,0.30)',
    borderRadius: 14,
    marginBottom: 2,
    paddingHorizontal: 10,
    paddingVertical: 3,
    alignSelf: 'flex-start',
    maxWidth: '90%',
  },
  
  optionsButton: {
    padding: 8,
    marginLeft: 8,
  },
  quantityModal: {
    position: 'absolute',
    bottom: 70,
    right: 10,
    backgroundColor: 'rgba(26, 26, 26, 0.95)',
    borderRadius: 12,
    padding: 12,
    zIndex: 3,
  },
  quantityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  quantityLabel: {
    color: '#fff',
    fontSize: 14,
    marginRight: 10,
  },
  quantityControls: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  titleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
});