import { StyleSheet } from 'react-native';


export const ACCENT_COLOR = '#E76A54';

export default StyleSheet.create({
    container: { flex: 1, backgroundColor: '#000' },
    video: { flex: 1 },
    chatOverlay: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      bottom: 0,
      paddingHorizontal: 12,
      paddingVertical: 8,
      backgroundColor: 'transparent', // ✅ allow blur to work
      overflow: 'hidden',
      zIndex: 40,
    },    
    message: { color: '#fff', fontSize: 14, lineHeight: 20, marginBottom: 4, paddingVertical: 1 },
    messageSender: {     fontWeight: 'bold',
      color: '#E76A54', },
    carouselCountdownLabel: { color: '#fff', fontSize: 14, marginBottom: 4 },
    carouselOption: { backgroundColor: '#333', paddingVertical: 8, paddingHorizontal: 12, marginRight: 8, borderRadius: 6 },
    carouselOptionSelected: { backgroundColor: ACCENT_COLOR },
    carouselOptionText: { color: '#fff', fontSize: 14 },
    modalButtonPrimary: { marginTop: 20, paddingVertical: 12, borderRadius: 8, alignItems: 'center', width: '100%', backgroundColor: ACCENT_COLOR },
    modalButtonSecondary: { marginTop: 20, paddingVertical: 12, borderRadius: 8, alignItems: 'center', width: '100%', borderWidth: 1, borderColor: ACCENT_COLOR },
    modalButtonTextPrimary: { color: '#fff', fontSize: 16, fontWeight: '600' },
    modalButtonTextSecondary: { color: ACCENT_COLOR, fontSize: 16, fontWeight: '600' },
    productCard: { marginRight: 10, backgroundColor: '#fff', borderRadius: 12, padding: 14, width: 100, alignItems: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.2, shadowRadius: 4, elevation: 4 },
    productImage: { width: 60, height: 60, borderRadius: 8, marginRight: 10 },
    productTitle: { fontSize: 15, fontWeight: 'bold', color: '#fff' },
    productPrice: { fontSize: 14, color: '#fff', marginTop: 2 },
    productQty: { fontSize: 14, color: '#999' },
    productPanel: { flexDirection: 'row', backgroundColor: '#1a1a1a', padding: 12, borderRadius: 16, marginHorizontal: 12, position: 'absolute', bottom: 100, left: 0, right: 0, alignItems: 'center' },
    productDetails: { flex: 1 },
    productMeta: { color: '#ccc', fontSize: 12, marginTop: 2 },
    timerBox: { backgroundColor: '#E76A54', paddingHorizontal: 14, paddingVertical: 6, borderRadius: 20, marginLeft: 10 },
    timerText: { color: '#000', fontWeight: 'bold', fontSize: 13 },
    selectedProduct: { position: 'absolute', bottom: 20, left: 10, right: 10, backgroundColor: '#222', padding: 12, borderRadius: 12, borderWidth: 2, borderColor: ACCENT_COLOR, zIndex: 999, elevation: 999 },
    selectedProductTitle: { fontSize: 16, fontWeight: 'bold', color: '#fff', marginBottom: 4 },
    selectedProductPrice: { fontSize: 14, color: '#ccc', marginBottom: 2 },
    selectedProductQty: { fontSize: 14, color: '#aaa' },
    countdownBadge: { position: 'absolute', top: 130, right: 20, backgroundColor: '#FFD700', paddingVertical: 4, paddingHorizontal: 10, borderRadius: 16, zIndex: 999, elevation: 4 },
    countdownText: { color: '#000', fontWeight: 'bold', fontSize: 13 },
    productPanelFull: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: 'transparent',
      zIndex: 20,
      elevation: 10,
      overflow: 'hidden',
      paddingVertical: 16,
    },
    productImageLarge: { width: 70, height: 70, borderRadius: 12, marginRight: 12 },
    strikePrice: { color: '#999', fontSize: 12, textDecorationLine: 'line-through', marginRight: 6 },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.7)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: '#222',
        padding: 16,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        maxHeight: '80%',
    },
    queueHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 20,
      paddingBottom: 12,
      borderBottomWidth: 1,
      borderBottomColor: 'rgba(255,255,255,0.1)',
    },
    queueTitle: {
      color: '#fff',
      fontSize: 20,
      fontWeight: '600',
    },
    queueStats: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    queueStatsText: {
      color: '#999',
      fontSize: 14,
      marginRight: 8,
    },
    rotatingBadge: {
      backgroundColor: ACCENT_COLOR,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
    },
    rotatingBadgeText: {
      color: '#fff',
      fontSize: 12,
      fontWeight: '600',
    },
    emptyQueue: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    emptyQueueText: {
      color: '#fff',
      fontSize: 18,
      fontWeight: '600',
      marginTop: 16,
    },
    emptyQueueSubtext: {
      color: '#999',
      fontSize: 14,
      textAlign: 'center',
      marginTop: 8,
    },
    queueItem: {
      flexDirection: 'row',
      backgroundColor: '#333',
      padding: 12,
      marginBottom: 12,
      borderRadius: 12,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 3,
    },
    queueItemActive: {
      backgroundColor: '#444',
      transform: [{ scale: 1.02 }],
      shadowOpacity: 0.3,
      shadowRadius: 6,
    },
    queueItemSelected: {
      borderWidth: 2,
      borderColor: ACCENT_COLOR,
    },
    queueItemDragHandle: {
      paddingRight: 12,
      justifyContent: 'center',
    },
    queueItemImage: {
      width: 50,
      height: 50,
      borderRadius: 8,
      backgroundColor: '#444',
    },
    queueItemContent: {
      flex: 1,
      marginLeft: 12,
    },
    queueItemTitle: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '500',
      marginBottom: 4,
    },
    queueItemDetails: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    queueItemPrice: {
      color: ACCENT_COLOR,
      fontSize: 14,
      fontWeight: '600',
      marginRight: 12,
    },
    queueItemQuantity: {
      color: '#999',
      fontSize: 13,
    },
    queueItemOrder: {
      alignItems: 'flex-end',
      marginLeft: 12,
    },
    queueItemNumber: {
      color: '#999',
      fontSize: 14,
      fontWeight: '600',
    },
    currentBadge: {
      backgroundColor: ACCENT_COLOR,
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 10,
      marginTop: 4,
    },
    currentBadgeText: {
      color: '#fff',
      fontSize: 11,
      fontWeight: '600',
    },
    queueActions: {
      marginTop: 20,
      borderTopWidth: 1,
      borderTopColor: 'rgba(255,255,255,0.1)',
      paddingTop: 20,
    },
    queueButton: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 14,
      borderRadius: 12,
      marginBottom: 12,
    },
    queueButtonPrimary: {
      backgroundColor: ACCENT_COLOR,
    },
    queueButtonSecondary: {
      backgroundColor: 'transparent',
      borderWidth: 1,
      borderColor: ACCENT_COLOR,
    },
    queueButtonTextPrimary: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '600',
    },
    queueButtonTextSecondary: {
      color: ACCENT_COLOR,
      fontSize: 16,
      fontWeight: '600',
    },

    emptyProductPanel: {
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(26, 26, 26, 0.95)',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.1)',
      elevation: 10,
      zIndex: 20, // Same z-index as productPanelFull
      marginHorizontal: 0, // ensure no margin blocks full width
      paddingHorizontal: 0,
    },
    emptyProductContent: {
      alignItems: 'center',
      padding: 20,
      maxWidth: 300,
    },
    emptyProductIcon: {
      marginBottom: 12,
      opacity: 0.9,
    },
    emptyProductTextContainer: {
      alignItems: 'center',
      marginBottom: 16,
    },
    emptyProductTitle: {
      color: '#fff',
      fontSize: 18,
      fontWeight: '600',
      marginBottom: 8,
      textAlign: 'center',
    },
    emptyProductDescription: {
      color: 'rgba(255, 255, 255, 0.7)',
      fontSize: 14,
      textAlign: 'center',
      lineHeight: 20,
    },
    emptyProductButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: ACCENT_COLOR,
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 3,
    },
    emptyProductButtonText: {
      color: '#fff',
      fontSize: 15,
      fontWeight: '600',
    },
    rotationControls: {
      backgroundColor: 'rgba(0,0,0,0.2)',
      borderRadius: 16,
      padding: 16,
      marginBottom: 20,
    },
    rotationTitle: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '600',
      marginBottom: 12,
    },
    timerScroll: {
      marginBottom: 16,
    },
    timerOption: {
      backgroundColor: 'rgba(255,255,255,0.1)',
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderRadius: 20,
      marginRight: 8,
    },
    timerOptionSelected: {
      backgroundColor: ACCENT_COLOR,
    },
    timerOptionText: {
      color: '#fff',
      fontSize: 14,
      fontWeight: '500',
    },
    rotationSetting: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 4,
    },
    rotationSettingText: {
      color: '#fff',
      fontSize: 14,
    },
    rotationSettingHint: {
      color: '#999',
      fontSize: 12,
    },
    optionsHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
      paddingBottom: 16,
      borderBottomWidth: 1,
      borderBottomColor: 'rgba(255,255,255,0.1)',
    },
    optionsTitle: {
      color: '#fff',
      fontSize: 20,
      fontWeight: '600',
    },
    closeButton: {
      padding: 8,
      borderRadius: 20,
      backgroundColor: 'rgba(255,255,255,0.1)',
    },
    optionsSection: {
      gap: 16,
    },
    optionCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(255,255,255,0.05)',
      padding: 16,
      borderRadius: 16,
      marginBottom: 12,
    },
    optionIconContainer: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: 'rgba(255,255,255,0.1)',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 16,
    },
    optionInfo: {
      flex: 1,
    },
    optionTitle: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '600',
      marginBottom: 4,
    },
    optionStatus: {
      color: '#999',
      fontSize: 14,
    },
    optionButton: {
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 20,
      marginLeft: 12,
    },
    optionButtonSuccess: {
      backgroundColor: '#4CAF50',
    },
    optionButtonDanger: {
      backgroundColor: '#ff4444',
    },
    optionButtonText: {
      color: '#fff',
      fontSize: 14,
      fontWeight: '600',
    },
    endStreamButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#e53935',
      padding: 16,
      borderRadius: 16,
      marginTop: 8,
    },
    endStreamIcon: {
      marginRight: 8,
    },
    endStreamText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '600',
    },
    preStreamContainer: {
      flex: 1,
      backgroundColor: '#000',
    },
    previewContainer: {
      height: '40%',
      backgroundColor: '#111',
    },
    previewVideo: {
      flex: 1,
    },
    previewPlaceholder: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#111',
    },
    previewPlaceholderText: {
      color: '#666',
      fontSize: 16,
      marginTop: 12,
    },
    setupContainer: {
      flex: 1,
      padding: 20,
      backgroundColor: '#1a1a1a',
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      marginTop: -20,
    },
    setupTitle: {
      color: '#fff',
      fontSize: 24,
      fontWeight: '600',
      marginBottom: 24,
    },
    setupChecklist: {
      marginBottom: 24,
    },
    checkItem: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(255,255,255,0.05)',
      padding: 16,
      borderRadius: 16,
      marginBottom: 12,
    },
    checkItemComplete: {
      backgroundColor: 'rgba(76,175,80,0.1)',
      borderColor: '#4CAF50',
      borderWidth: 1,
    },
    checkIconContainer: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: 'rgba(255,255,255,0.1)',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 16,
    },
    checkContent: {
      flex: 1,
    },
    checkTitle: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '600',
      marginBottom: 4,
    },
    checkDescription: {
      color: '#999',
      fontSize: 14,
    },
    streamInfo: {
      backgroundColor: 'rgba(255,255,255,0.05)',
      padding: 16,
      borderRadius: 16,
      marginBottom: 24,
    },
    streamInfoTitle: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '600',
      marginBottom: 12,
    },
    streamInfoItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    streamInfoLabel: {
      color: '#999',
      fontSize: 14,
    },
    streamInfoValue: {
      color: '#fff',
      fontSize: 14,
      fontWeight: '500',
    },
    startStreamButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: ACCENT_COLOR,
      padding: 16,
      borderRadius: 16,
      marginTop: 'auto',
    },
    startStreamButtonDisabled: {
      backgroundColor: '#666',
      opacity: 0.7,
    },
    startStreamIcon: {
      marginRight: 8,
    },
    startStreamText: {
      color: '#fff',
      fontSize: 18,
      fontWeight: '600',
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
      minHeight: 200,
    },
    loadingText: {
      color: '#fff',
      fontSize: 16,
      marginTop: 12,
    },
    emptyText: {
      color: '#999',
      fontSize: 16,
      textAlign: 'center',
      padding: 20,
    },
    searchContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(255,255,255,0.1)',
      borderRadius: 12,
      paddingHorizontal: 12,
      marginBottom: 16,
      height: 40,
    },
    searchIcon: {
      marginRight: 8,
    },
    searchInput: {
      flex: 1,
      color: '#fff',
      fontSize: 16,
      padding: 0,
    },
    broadcasterHeaderRow: {
      position: 'absolute',
      top: 60,
      left: 20,
      right: 20,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      zIndex: 999,
    },
    
    viewerCountPill: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(231, 106, 84, 0.3)',  // Translucent orange
      borderWidth: 1,
      borderColor: '#E76A54',
      borderRadius: 15,
      paddingHorizontal: 11,
      paddingVertical: 5,
      marginRight: 10,
    },
    
    broadcasterHeaderIcons: {
      flexDirection: 'row',
      alignItems: 'center',
      zIndex: 1000,
    },
    
    iconButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(231, 106, 84, 0.3)',
      borderWidth: 1,
      borderColor: '#E76A54',
      borderRadius: 15,
      paddingHorizontal: 11,
      paddingVertical: 5,
      marginRight: 10,
      zIndex: 1000,
    },    
    
    viewerCountText: {
      color: '#fff',
      fontSize: 14,
      fontWeight: '600',
    },
  });